// ─────────────────────────────────────────────────────────────────
// SYNCED FILE — DO NOT EDIT BY HAND.
// Generated by mcp-server/scripts/bundle-data.ts from the main
// Sakina app. Source of truth: ../../../src/lib/utils/<filename>.
// Run `npm run bundle-data` to refresh.
// ─────────────────────────────────────────────────────────────────

/**
 * Arabic text normalisation (WO#97 §S3B).
 *
 * Collapses common spelling and diacritical variants so the
 * substring-based crisis / distress detectors match consistently
 * regardless of how the user types. Without this, "أبي أموت" (with
 * hamza) and "ابي اموت" (chat-typed, no hamza) diverge — the second
 * form is what most users actually produce on a phone keyboard, but
 * the curated keyword list historically matched the formal MSA spelling.
 *
 * Operations (in order):
 *   1. NFKD-decompose, then strip combining marks (tashkeel /
 *      diacritics like fatha, kasra, damma, sukun, tanwin, shadda).
 *   2. Strip the standalone Arabic diacritic ranges that survive NFKD
 *      (small letters / Quranic annotation marks). The escaped
 *      ranges below cover U+0610–061A, U+064B–065F, U+0670, and the
 *      Quranic-annotation block U+06D6–U+06ED.
 *   3. Normalise hamza variants (إ أ آ) to bare alif (ا).
 *   4. Normalise taa marbuta (ة) to haa (ه). This is the dominant
 *      chat convention — "روحي طالعة" → "روحي طالعه".
 *   5. Normalise alif maqsura (ى) to ya (ي).
 *   6. Strip tatweel / kashida (ـ) which is purely decorative.
 *   7. Collapse internal whitespace + trim.
 *
 * What is intentionally NOT normalised:
 *   - Letter shapes like teh-with-three-dots vs teh — those carry
 *     real phonemic distinctions in Persian / Urdu and would over-
 *     collapse.
 *   - Latin-script content. ASCII passes through unchanged so the
 *     existing English / transliterated keywords match exactly.
 *
 * The function is locale-agnostic: it can be called on any string.
 * Strings with no Arabic codepoints come out the same except for
 * collapsed whitespace and trim. That property is what lets the
 * crisis detector apply normalisation unconditionally to the user's
 * input (`text`) — only the per-keyword comparison branches on
 * Arabic-vs-not.
 */

// Combining diacritics + Quranic annotation marks. These ranges are
// what NFKD does NOT decompose (Arabic diacritics are atomic, not
// composed) so we strip them explicitly.
//
//   U+0610–061A  Arabic small letters / annotation
//   U+064B–065F  Tashkeel (fatha, kasra, damma, shadda, tanwin etc.)
//   U+0670       Superscript alef
//   U+06D6–06ED  Quranic annotation signs (sukun, hamza-above, etc.)
const ARABIC_DIACRITIC_REGEX = /[ؐ-ًؚ-ٰٟۖ-ۭ]/g

const HAMZA_FORMS_REGEX = /[آأإ]/g // آ أ إ → ا
const TAA_MARBUTA_REGEX = /ة/g                // ة → ه
const ALIF_MAQSURA_REGEX = /ى/g               // ى → ي
const TATWEEL_REGEX = /ـ/g                    // ـ → (removed)

// WO#252-A cross-script fold (Gem 2 spec). Collapse the Persian/Urdu-keyboard
// codepoints onto their Arabic-keyboard equivalents so an Urdu-keyboard user and
// an Arabic-keyboard user typing the same word match the same keyword. These are
// keyboard/orthographic variants, NOT phonemic distinctions:
//   • Persian/Urdu yeh  ی U+06CC → Arabic yeh  ي U+064A
//   • Persian/Urdu keheh ک U+06A9 → Arabic kaf ك U+0643
//   • Urdu noon-ghunna  ں U+06BA → Arabic noon ن U+0646
const PERSIAN_YEH_REGEX = /ی/g
const PERSIAN_KEH_REGEX = /ک/g
const NOON_GHUNNA_REGEX = /ں/g

/**
 * Apply the WO §S3B normalisation pipeline. Pure function.
 */
// WO#263 (Gem 5 ruling) — strip ZWNJ (U+200C). Keyboards emit ZWNJ-joined
// Persian compound verbs (e.g. the mi- prefix) that the non-ZWNJ stored form
// misses. Zero-width + orthographic (not phonemic); no keyword's identity
// depends on it, and Arabic (ar) keywords never contain it — so the strip is
// safe for the shared Arabic-script branch. Applied to both keyword and input.
const ZWNJ_REGEX = /\u200C/g

export function normaliseArabic(text: string): string {
  if (!text) return ''

  // NFKD strips composed diacritics that ARE decomposable. Most
  // Arabic tashkeel are not composable, so step 2 (regex strip)
  // does the real work, but NFKD covers any latin diacritics that
  // might appear in the same string.
  const decomposed = text.normalize('NFKD')

  return decomposed
    .replace(ZWNJ_REGEX, '') // WO#263 — strip ZWNJ (U+200C) before folds
    .replace(ARABIC_DIACRITIC_REGEX, '')
    .replace(HAMZA_FORMS_REGEX, 'ا') // bare alif
    .replace(TAA_MARBUTA_REGEX, 'ه') // haa
    .replace(ALIF_MAQSURA_REGEX, 'ي') // ya
    .replace(PERSIAN_YEH_REGEX, 'ي') // ی → ي (cross-keyboard, WO#252-A)
    .replace(PERSIAN_KEH_REGEX, 'ك') // ک → ك
    .replace(NOON_GHUNNA_REGEX, 'ن') // ں → ن
    .replace(TATWEEL_REGEX, '')
    .replace(/\s+/g, ' ')
    .trim()
}

/**
 * Cheap test — does this string contain any Arabic-block codepoints?
 * Used by the detectors to decide whether to normalise a keyword
 * before substring-checking against the (already-normalised) input.
 *
 * Range: U+0600–U+06FF (basic Arabic block, including dialect chars).
 * This is a fast precheck, not a strict language detector.
 */
export function containsArabic(text: string): boolean {
  return /[؀-ۿ]/.test(text)
}
