// ─────────────────────────────────────────────────────────────────
// SYNCED FILE — DO NOT EDIT BY HAND.
// Generated by mcp-server/scripts/bundle-data.ts from the main
// Sakina app. Source of truth: ../../../src/lib/utils/<filename>.
// Run `npm run bundle-data` to refresh.
// ─────────────────────────────────────────────────────────────────

/**
 * Crisis Detection Utility
 *
 * Single source of truth for crisis-keyword routing across:
 *   - client: speak-to-me.tsx
 *   - server: api/ai/match-situation/route.ts (halt + route to crisis modal)
 *   - server: api/comfort/route.ts via getSoulComfort (append helplines to
 *     verse-of-comfort response; UX is intentionally different from
 *     match-situation — see WO#73 for the rationale and out-of-scope notes
 *     on a possible future halt+route unification)
 *
 * Checks user input for crisis keywords BEFORE reaching the AI verse-matching
 * engine. Differentiates self-harm/suicidal ideation from abuse/domestic
 * violence, routing to appropriate support screens.
 *
 * IMPORTANT: Self-harm is prioritised over abuse when both are detected,
 * as it represents the more acute danger.
 *
 * Keyword lists cover English, Indonesian (informal kamu register),
 * Urdu (transliterated), Arabic (MSA + dialects), and a small set of
 * common misspellings for the most acute English phrases.
 *
 * ── Gem 3 + Gem 5 joint review (6 May 2026, WO#94) ─────────────────
 *
 * The list was rebalanced for both clinical safety AND cultural
 * accuracy. Highlights:
 *
 *   - REMOVED: 'يا ليتني مت' — exact Quranic phrasing (Maryam, Surah
 *     Maryam 19:23). Users quoting the verse were being hard-routed
 *     to a suicide hotline. High false-positive — moved out of the
 *     hard-route gate.
 *   - REMOVED: 'يا رب خذني' / 'يا رب خذ أمانتك' — theological
 *     euphemisms used casually by older Arabic speakers as daily
 *     exasperation. These will be re-handled by the future High
 *     Distress flow (empathetic validation + Islamic comfort + soft
 *     offer of professional help, NOT a hard hotline route).
 *   - REMOVED: 'marta hai' / 'marti hai' — colloquially "has a crush
 *     on" in Urdu/Hindi. Replaced by `'mujhe marta hai'` /
 *     `'mujhe marti hai'` which require an explicit object pronoun.
 *   - ADDED: Arabic dialect coverage (Egyptian, Gulf, Levantine) —
 *     MSA-only lists missed >70% of real distress phrasing in those
 *     populations. See the dialect block below.
 *   - ADDED: Indonesian slang — `'bundir'`, `'gak kuat lagi'` are the
 *     dominant chat-typed forms in 18–30 distress contexts (Gem 5).
 *   - ADDED: Method-specific terms across all locales — `'overdose'`,
 *     `'jump off'`, `'minum racun'`, `'gantung diri'`, `'zeher kha
 *     lungi'` etc. Method specificity correlates strongly with
 *     planning intent (Gem 3).
 *   - ADDED: 'KDRT' (Indonesian acronym for Kekerasan Dalam Rumah
 *     Tangga, domestic violence). Stored as `'kdrt'` so the existing
 *     `text.toLowerCase()` step matches any case the user types.
 *   - DEFERRED: pan-Arab helpline routing requires geolocation; no
 *     usable single-Arabic helpline exists. Tracked as a future WO.
 *
 * ── Earlier P0 patches (preserved) ─────────────────────────────────
 * WO#91 Session 2 added `'end it all'` / `'want to end it all'` after
 * airplane-mode QA exposed the gap between `'ending it all'` and the
 * common verb form.
 *
 * Layer 3 (the Gemini classifier) holds an additional theological
 * exception for purely abstract spiritual discussions — see the
 * SYSTEM_PROMPT in api/ai/match-situation/route.ts.
 */

export type CrisisType = 'self-harm' | 'abuse' | 'none'

export interface CrisisDetectionResult {
  isCrisis: boolean
  crisisType: CrisisType
}

export const SELF_HARM_KEYWORDS = [
  // ── English — explicit ideation ─────────────────────────────────────────
  'kill myself', 'want to die', 'end my life', 'suicide',
  'better off dead', 'no reason to live', 'hurt myself', 'harm myself',
  'cutting myself', 'self harm', 'self-harm',
  // WO#94 Gem 3 — explicit + method-specific additions. Method
  // specificity correlates with planning intent.
  'take my own life', 'swallow pills', 'overdose', 'jump off',
  // WO#94 Gem 3 — common misspelling that catches "suicidal" /
  // "suicide" stems before the t/e is typed.
  'suicid',

  // ── WO#128 Gem 3 — present-continuous / -ing verb forms ─────────────
  // The base-verb keywords above ("hurt myself", "harm myself") fail
  // substring-match against the gerund forms ("hurting myself") because
  // there's no space between "hurt" and "myself" in the gerund. Architect
  // red-team P1-1 finding. Gem 3 approved (WO#128 brief) the gerund
  // additions across all five primary verbs:
  'hurting myself', 'harming myself', 'killing myself',
  'punishing myself', 'starving myself',

  // ── English — passive ideation ──────────────────────────────────────────
  'want to disappear', 'i am a burden', 'no way out',
  'no point anymore', "can't go on", 'give up on life',
  'nobody would miss me', 'better without me', 'better off without me',
  "wish i wasn't here", 'wish i was never born',
  // WO#128 Gem 3 — perceived-burdensomeness additions. "i'm a burden"
  // is the contraction form of the existing "i am a burden"; the longer
  // "everyone would be better off without me" catches the full sentence
  // that the existing "better off without me" substring-matches only
  // when typed as "without me" (i.e. the full longer sentence is a
  // stricter, also-acceptable match).
  "i'm a burden", 'everyone would be better off without me',
  'wish i could disappear',
  // WO#308 (Gem 3) — negated-existence / passive-ideation additions. Full
  // clauses only, never bare fragments. Four ratified phrasings already fire and
  // are intentionally NOT re-listed: "wish i was never born" and
  // "better off without me" (existing keywords), "want to end it all" (existing),
  // "sleep and never wake up" (via the existing 'never wake up'). Apostrophe forms
  // below also match the un-apostrophized spelling (see stripApostrophes).
  "wish i didn't exist", "hope i don't wake up", "can't do life anymore",
  'wish allah would take me', 'asking allah to take my life',

  // ── English — verb / wish forms (Round 4 expansion) ────────────────────
  'feel like dying', 'feeling like dying',
  'wish i could die', 'wish i was dead', "wish i'd die",
  "don't want to be alive", "don't want to wake up", "don't want to live",
  "don't want to exist",
  'done with life', 'tired of living', 'tired of being alive',
  'want it to end', 'ending it all', 'thinking about ending it', 'end this life',
  // WO#91 Session 2 P0 patch — surfaced during airplane-mode QA.
  // "I want to end it all" did not match any of the existing keywords
  // (closest neighbour `ending it all` fails substring match against
  // `end it all`). Added the colloquial idiom + the verb form so the
  // phrase fires Layer-1 detection client-side, before any offline
  // search is reached. Reviewed and retained by Gem 3 in WO#94.
  'end it all', 'want to end it all',
  'feeling suicidal', 'suicidal thoughts', 'thoughts of suicide',
  'go to sleep and not wake up', 'never wake up',

  // ── Indonesian (Bahasa Indonesia — informal kamu register) ─────────────
  'bunuh diri', 'ingin mati', 'pengen mati', 'akhiri hidup',
  'lebih baik mati', 'ingin hilang saja', 'semoga aku mati',
  'sudah tidak kuat hidup', 'capek hidup', 'menyerah hidup',
  'tidak ada gunanya hidup', 'tidak ingin hidup',
  'ingin menghilang', 'aku beban',
  // Indonesian self-harm verbs (Gem 3 pastoral expansion — colloquial
  // chat-typed forms common in distress contexts; ngelukain is the
  // colloquial/chat form of melukai)
  'menyakiti diri', 'melukai diri', 'ngelukain diri', 'menyiksa diri',
  // WO#94 Gem 3 + Gem 5 — Indonesian slang + method-specific.
  // 'bundir' is the dominant chat abbreviation of 'bunuh diri';
  // 'gak kuat lagi' ("not strong enough anymore") is high-frequency
  // distress slang per Gem 5; 'minum racun' / 'gantung diri' are
  // method-specific.
  'bundir', 'pengen bundir', 'gak kuat lagi',
  'minum racun', 'gantung diri',

  // ── Urdu (transliterated) ──────────────────────────────────────────────
  'khudkushi', 'marna chahta', 'marna chahti', 'zindagi khatam',
  'marne ka dil', 'kash main mar jaun', 'mout aa jaye',
  'zindagi se tang', 'jeenay ka koi maqsad nahi', 'thak gaya hoon zindagi se',
  'zindagi ka koi matlab nahi', 'ghayab hona chahta',
  // Urdu jina-negation forms (masculine + feminine) with common Pakistani
  // romanization variants (jina/jeena, nahi/nahin). Matching is exact
  // substring on lowercased input, so phonetic variants must be explicit.
  'jina nahi chahta', 'jina nahin chahta',
  'jeena nahi chahta', 'jeena nahin chahta',
  'jina nahi chahti', 'jina nahin chahti',
  'jeena nahi chahti', 'jeena nahin chahti',
  // WO#94 Gem 3 + Gem 5 — Urdu wish forms + method-specific.
  // 'zeher kha lungi' ("I will eat poison") is a culturally common
  // expression per Gem 5 — high specificity, low false positive.
  'khatam karna chahta', 'khatam kar dungi',
  'zeher kha lungi', 'zeher khana', 'jaan leni',

  // ── Arabic (MSA) — stored in normaliseArabic() form (WO#97 §S3D) ──────
  // The detector applies the same normalisation to user input, so
  // chat-typed Arabic without hamza / tashkeel matches the formal
  // MSA spellings the Gems originally reviewed. See
  // src/lib/utils/arabic-normalise.ts for the operation list.
  // Direct
  'اريد ان اموت', 'انتحر', 'بنتحر', 'انهي حياتي',
  // Wish
  'اتمني الموت',
  // (Removed by WO#94 Gem 3: 'يا ليتني مت' — exact Quranic phrasing
  //  from Surah Maryam 19:23, false-positive when users quote the verse.)
  // Done-with-life
  'تعبت من الحياه', 'ما لي خلق اعيش',
  // (Removed by WO#94 Gem 3 + Gem 5: 'يا رب خذني' / 'يا رب خذ أمانتك'
  //  — theological euphemisms used casually as daily exasperation by
  //  older speakers. Routed instead to the future High Distress flow.)

  // ── WO#128 Gem 3 — Islamic-specific crisis phrases ────────────────
  // These are theologically-coded direct-ideation phrases that the
  // earlier theological-euphemism removals (يا رب خذني / يا رب خذ
  // أمانتك) deliberately did NOT cover. Gem 3 classified these as
  // CRISIS rather than HIGH_DISTRESS because they're addressed to
  // Allah but request death rather than rescue, lifting them out of
  // the casual-exasperation register.
  'الله ياخذني',   // "May Allah take me"
  'يا رب اموت',    // "Oh Lord let me die"

  // ── WO#252-A (Decision A) — moved BACK from the soft high-distress tier ──
  // All self-directed death-wishes now route to the single crisis screen. These
  // two theological euphemisms ("take me" / "take back Your trust") were held in
  // detectHighDistress (WO#94/95) as casual exasperation; Decision A rules them
  // to the crisis screen. Full phrases (never bare خذني) bound the substring
  // over-match. Stored in normaliseArabic() form (أمانتك → امانتك).
  'يا رب خذني',        // "Oh Lord, take me"
  'يا رب خذ امانتك',   // "Oh Lord, take back Your trust (my soul)"

  // ── Arabic dialects (WO#94 Gem 3, normalised by WO#97 §S3D) ───────────
  // MSA alone misses the majority of real distress phrasing across
  // Gulf, Levant, and Egypt. The five dialect entries below were
  // verified by Gem 3 as direct ideation in their respective dialects.
  'ابي اموت',          // Gulf — "I want to die"
  'مابي اعيش',         // Gulf — "I don't want to live"
  'بدي موت',           // Levantine — "I want to die"
  'عايز اموت',         // Egyptian — "I want to die"
  'نفسي اموت',         // Egyptian — "I wish I'd die"

  // ── WO#97 §S3C — chat-typed dialectal expansion.
  // Gem 3 signed off (WO#189): 5 keep, 3 demoted/removed pending soft-tier, 1 dropped.
  // Substring-matched against normaliseArabic(input), so users who
  // type without hamza / diacritics — i.e. virtually all phone keyboard
  // input — fire the same gate as users typing in formal MSA.
  'ابغي اموت',         // Gulf variant of "I want to die"
  'ما ابي اعيش',       // Gulf negation with explicit "ما"
  'بدي اموت',          // Levantine variant
  'مش عايز اعيش',      // Egyptian negation
  'ما بدي اعيش',       // Levantine negation

  // ── Turkish — WO#145-B ──────────────────────────────────────────
  'kendimi öldüreceğim', 'ölmek istiyorum', 'hayatıma son vereceğim',
  'intihar', 'ölsem daha iyi', 'yaşamak için bir nedenim yok',
  'kendime zarar vereceğim', 'kendimi keseceğim', 'kendimi kesiyorum',
  'yaşamaya değmez', 'canıma kıyacağım', 'hap içeceğim',
  'ilaç içeceğim', 'yüksek doz', 'atlayacağım',
  'intihar edeceğim', 'kendimi cezalandırıyorum', 'aç bırakıyorum',
  'yok olmak istiyorum', 'ortadan kaybolmak istiyorum', 'ben bir yüküm',
  'herkese yük oluyorum', 'çıkış yolu yok', 'artık hiçbir şeyin anlamı yok',
  'acıya dayanamıyorum', 'yaşamaya dayanamıyorum', 'devam edemiyorum',
  'hayattan vazgeçtim', 'kimse beni özlemezdi', 'bensiz daha iyiler',
  'yaşamak istemiyorum', 'canıma tak etti', 'her şeyi bitirmek istiyorum',
  'kendimden nefret ediyorum', 'intahar', 'intihar edicem',
  'ölicem', 'ölecem', 'kendimi asıcam',
  'yaşamak haram oldu',

  // ── Persian / Farsi (fa) — WO#212 A2 ────────────────────────────
  // Stored in normaliseArabic() form (آ→ا etc.) so chat-typed input,
  // which the detector also normalises, matches. Persian letters
  // (ک U+06A9, ی U+06CC, پ چ ژ گ) are NOT collapsed by normaliseArabic
  // and are stored as Persian-keyboard output. Gem 3 (tier) + Gem 5
  // (strings) VERIFIED - WO#266 locked ruling; fa self-harm stays crisis.
  // Bare noun خودکشی ("suicide") is frame-gated (WO#265 four-gate).
  'خودکشی',                  // "suicide"
  'خودکشی میکنم',            // "I will commit suicide"
  'میخوام بمیرم',            // "I want to die" (colloquial)
  'میخواهم بمیرم',           // "I want to die" (formal)
  'کاش بمیرم',               // "I wish I'd die"
  'کاش مرده بودم',           // "wish I were dead"
  'نمیخوام زنده باشم',       // "I don't want to be alive"
  'به زندگیم پایان میدم',    // "I'll end my life"
  'به خودم اسیب میزنم',      // "I hurt myself" (آسیب normalised → اسیب)
  'به خودم صدمه میزنم',      // "I harm myself"
  'دلیلی برای زندگی ندارم',  // "no reason to live"
  'از زندگی خسته شدم',       // "tired of life"

  // ── Bengali (bn) — WO#212 A2 ────────────────────────────────────
  // Separate Unicode block (U+0980–09FF); matched via lowercase
  // substring (no Arabic normalisation). Gem 3 (tier) + Gem 5 (strings)
  // VERIFIED - WO#266 locked ruling; bn self-harm stays crisis. Bare noun
  // আত্মহত্যা ("suicide") is frame-gated (WO#265 four-gate).
  'আত্মহত্যা',               // "suicide"
  'আত্মহত্যা করব',           // "I will commit suicide"
  'মরতে চাই',                // "want to die"
  'মরে যেতে চাই',            // "I want to die"
  'জীবন শেষ করে দিতে চাই',   // "end my life"
  'নিজেকে শেষ করে দিতে চাই', // "I want to end myself"
  'বেঁচে থাকতে চাই না',      // "don't want to live"
  'নিজের ক্ষতি করি',         // "I harm myself"
  'নিজেকে আঘাত করি',         // "I hurt myself"
  'বাঁচার কোনো মানে নেই',    // "no reason to live"


  // ═══ WO#252-B — Architect-approved crisis expansion (self-harm) ═══════════════
  // Net-new keywords from the reviewed Gem 2/3/4/5 candidate union, diffed
  // against the live post-252-A detector. Arabic stored in normaliseArabic()
  // form; Latin/transliterated lower-cased. Both folded again defensively by
  // matchesAny at match time.
  // ── EN ──
  "i want to end it",
  "nothing to live for",
  "want to sleep forever",
  "no point living",
  "kms",
  "cant take this anymore",
  "cut myself",
  "took a lot of pills",
  "allah take me",
  "pray allah takes me",
  "is it haram to end it",
  "dua to die in sleep",
  "will i go to hell if i",
  // ── TR ──
  "hayatıma son",
  "uyuyup uyanmamak",
  "allah canımı alsın",
  "dayanamıyorum artık",
  "kurtulmak istiyorum",
  "her şeyi bitirmek",
  "kendime zarar",
  "allah belamı versin",
  "nefes alamıyorum",
  "imtihana dayanamıyorum",
  // ── ID ──
  "pengen hilang",
  "mending mati",
  "tidak kuat lagi",
  "ga kuat lagi",
  "mau pergi jauh",
  "nyilet",
  "mo mati aja",
  "putus asa bgt",
  "doa agar cepat mati",
  "tidak kuat cobaan",
  // ── UR ──
  "مين مرنا چاہتا ہون",
  "مرنا چاہتا ہون",
  "مرنا چاہتي ہون",
  "اپني جان لے لون",
  "زندگي سے تنگ",
  "جينے كا دل نہين",
  "موت ا جايے",
  "زندگي ختم",
  "جينے كا مقصد",
  "تھك گيا ہون",
  "ميري جان نكل جايے",
  "زہر كھا لون",
  "زندہ نہين رہنا",
  "جان دے دون",
  "رگ كاٹ لي",
  "اللہ مجھے اٹھا لے",
  "زندگي عذاب ہے",
  "موت كي دعا",
  // ── AR ──
  "الانتحار",
  "انتحار",
  "اريد اموت",
  "اقتل نفسي",
  "مالي خلق اعيش",
  "الموت ارحم",
  "اريد ارتاح",
  "تعبت من الدنيا",
  "بموت نفسي",
  "ذبحت عمري",
  "اقطع شراييني",
  "هل الانتحار كفر",
  "دعاء الموت",
  "يا رب خدني",
  "يا ليتني مت",

  // ── WO#264 — fa/bn dialect additions (Gem 5 string + Gem 3 tier) ──
  // dialect additions — Gem 5 string + Gem 3 tier (fa self-harm), WO#264
  'نمیخواهم زنده باشم',
  'به زندگیم پایان میدهم',
  // dialect additions — Gem 5 string + Gem 3 tier (bn self-harm), WO#264
  'আত্মহত্যা করবো',
  'মইরা যাইতে চাই',
  'মইরা যেতে চাই',
  'নিজের ক্ষতি করব',
  'নিজের ক্ষতি করবো',
  'নিজেকে আঘাত করব',
  'নিজেকে আঘাত করবো',

  // ── Punjabi / Shahmukhi (pa) — WO#284 (Gem 2 byte-verified) ─────────
  // Pakistani Punjabi Muslim audience, RTL Shahmukhi. Full phrases only —
  // fire directly via matchesAnyExcept, never routed through bare-noun
  // suppression. See PA_SUPPRESS for the substring-collision nouns
  // deliberately kept OUT of the trigger lists (guard-before-trigger).
  'میں مرنا چاہندا',
  'میں مرنا چاہندی',
  'اپنے آپ نوں ختم',
  'جینے توں تنگ',
  'ربا مینوں چُک لے',
  'کوئی فائدہ نہیں جینے دا',
  'میں جان دے دینی',
  'کاش میں پیدا ای نہ ہوندا',
]

export const ABUSE_KEYWORDS = [
  // ── English ─────────────────────────────────────────────────────────────
  'he hits me', 'she hits me', 'being abused', 'afraid to go home',
  'sexually abused', 'assaulted', 'raped', 'beats me',
  'afraid of him', 'afraid of her', 'he hurts me', 'she hurts me',
  'domestic violence', 'forced me',
  // WO#94 Gem 3 — contextualised fear + coercive control + sexual abuse
  // precision. The "scared of my X" forms catch first-person fear
  // expressions that the older "afraid of him/her" patterns miss when
  // users name the perpetrator directly.
  'scared of my husband',
  'scared of my dad',
  'scared of my parents',
  'touches me inappropriately',
  "won't let me leave",

  // WO#187 Gem 3 — coercive/financial-control. The language victims use
  // before they would ever name it "abuse": coercive control, isolation,
  // document confiscation, and financial entrapment.
  'walking on eggshells',
  'took my passport',
  "won't let me see my family",
  'controls my money',

  // ── WO#128 Gem 3 — relationship-specific abuse patterns ─────────────
  // Architect red-team P1-1 finding. The existing "he hits me" / "she
  // hits me" patterns missed first-person reports that named the
  // perpetrator directly ("my husband hits me", "my father beats me").
  // Gem 3 approved adding the explicit-relationship forms across the
  // common abuser categories. Pastoral guidance: never reply with
  // "sabr" (patience) to active abuse — physical safety over family
  // unity. The crisis modal already routes to /find-support's
  // domestic-violence helpline list; no copy change needed.
  'husband hits me', 'husband beats me',
  'wife hits me', 'wife beats me',
  'father hits me', 'father beats me',
  'mother hits me', 'mother beats me',
  'partner hits me', 'partner beats me',
  'parent hits me', 'parents hit me',
  'brother hits me', 'brother beats me',
  'uncle hits me', 'uncle beats me',
  'in-laws hit me', 'in-laws beat me',
  'mother-in-law hits me', 'mother-in-law beats me',

  // ── Indonesian ──────────────────────────────────────────────────────────
  'dipukul', 'dilecehkan', 'diperkosa', 'takut pulang',
  'kekerasan rumah tangga',
  // WO#94 Gem 3 — KDRT acronym. Stored lowercase because detectCrisis
  // applies text.toLowerCase() before substring check, so any case the
  // user types ("KDRT", "Kdrt", "kdrt") matches.
  'kdrt',

  // ── Urdu (transliterated) ──────────────────────────────────────────────
  // (Removed by WO#94 Gem 3 + Gem 5: 'marta hai' / 'marti hai' —
  //  colloquially "has a crush on", high false positive. Replaced by
  //  the explicit-pronoun forms below.)
  'tashadud', 'ziadti',
  'ghar jane se darta', 'ghar jane se darti',
  // WO#94 Gem 3 — explicit-pronoun replacements + additional abuse
  // verbs that disambiguate the romanised stem.
  'mujhe marta hai',
  'mujhe marti hai',
  'hath uthata hai',
  'zabardasti ki',

  // ── Arabic (WO#94 Gem 3) — already in normaliseArabic() form ──────────
  // None of these contain hamza / taa-marbuta / tashkeel so the
  // pre-normalised storage is identical to the source spelling.
  'يضربني',  // "He hits me"
  'يعنفني',  // "He abuses me"
  'تحرش',    // "Harassment / assault"

  // ── Turkish — WO#145-B ──────────────────────────────────────────
  'bana vuruyor', 'şiddet görüyorum', 'eve gitmeye korkuyorum',
  'cinsel istismar', 'taciz edildim', 'tecavüze uğradım',
  'beni dövüyor', 'ondan korkuyorum', 'canımı yakıyor',
  'aile içi şiddet', 'beni zorladı', 'eşimden korkuyorum',
  'kocamdan korkuyorum', 'babamdan korkuyorum', 'ailemden korkuyorum',
  'bana dokunuyor', 'taciz ediyor', 'gitmeme izin vermiyor',
  'kocam bana vuruyor', 'kocam beni dövüyor', 'karım bana vuruyor',
  'eşim beni dövüyor', 'babam bana vuruyor', 'babam beni dövüyor',
  'annem bana vuruyor', 'sevgilim bana vuruyor', 'sevgilim beni dövüyor',
  'dışarı çıkmama izin vermiyor', 'beni tehdit ediyor', 'abim beni dövüyor',
  'dayak yiyorum', 'bana el kaldırıyor', 'zorla dokunuyor',

  // ── Persian / Farsi (fa) — WO#212 A2 (Gem 3/5 VERIFIED, WO#266) ────
  // Bare nouns خشونت خانگی + ازار جنسی are frame-gated (WO#265 four-gate).
  'کتکم میزنه',              // "he beats me" (colloquial)
  'کتکم میزند',              // "he beats me" (formal)
  'منو میزنه',               // "he hits me"
  'خشونت خانگی',             // "domestic violence"
  'میترسم برم خونه',         // "afraid to go home"
  'بهم تجاوز کرد',           // "he raped me"
  'ازار جنسی',               // "sexual abuse" (آزار normalised → ازار)

  // ── Bengali (bn) — WO#212 A2 (Gem 3/5 VERIFIED, WO#266) ───────────
  // Bare nouns পারিবারিক সহিংসতা + যৌন নির্যাতন are frame-gated (WO#265 four-gate).
  'আমাকে মারে',              // "he hits / beats me"
  'আমাকে মারধর করে',         // "he beats me"
  'ঘরে ফিরতে ভয় পাই',       // "afraid to go home"
  'পারিবারিক সহিংসতা',       // "domestic violence"
  'আমাকে ধর্ষণ করেছে',       // "he raped me"
  'ধর্ষিত হয়েছি',           // "I was raped"
  'যৌন নির্যাতন',            // "sexual abuse"


  // ═══ WO#252-B — Architect-approved crisis expansion (abuse) ═══════════════
  // Net-new keywords from the reviewed Gem 2/3/4/5 candidate union, diffed
  // against the live post-252-A detector. Arabic stored in normaliseArabic()
  // form; Latin/transliterated lower-cased. Both folded again defensively by
  // matchesAny at match time.
  // ── EN ──
  "he hit me",
  "physically abusive",
  "emotionally abusive",
  "forced to marry",
  "husband is violent",
  "dad hurts me",
  "locked me in",
  "he choked me",
  "sin to leave abusive husband",
  "forcing me to sleep with him",
  "break family ties for safety",
  // ── TR ──
  "kocam dövüyor",
  "babam vuruyor",
  "tehdit ediyor",
  "bana taciz",
  "evde şiddet",
  "zorla evlendiriliyorum",
  "zorla evlendirdiler",
  "abim dövüyor",
  "şiddet uyguluyor",
  "eve gitmekten korkuyorum",
  "hapis gibiyim",
  "beni dövdü",
  "kocam dövüyor boşanmak günah mı",
  "babam vuruyor hakkı var mı",
  "zulme sabretmek",
  "itaat etmek zorunda mıyım",
  // ── ID ──
  "suami memukul",
  "pelecehan",
  "bapak kasar",
  "diancam suami",
  "diancam",
  "dipaksa menikah",
  "dipaksa nikah",
  "dikurung",
  "dikunciin",
  "bapak main tangan",
  "disiksa",
  "suami kasar",
  "ga berani lapor",
  "suami pukul istri hukum islam",
  "dipaksa suami",
  "harus taat walau disiksa",
  // ── UR ──
  "ميرا شوہر مجھے مارتا ہے",
  "شوہر مارتا ہے",
  "مجھے مار پڑتي ہے",
  "گھريلو تشدد",
  "زبردستي كرتا ہے",
  "گاليان ديتا ہے",
  "مجھے ڈر لگتا ہے",
  "باپ مارتا ہے",
  "باپ نے مارا",
  "گھر مين ظلم",
  "زبردستي شادي",
  "مار پيٹ",
  "باہر نہين جانے ديتے",
  "خوف اتا ہے",
  "گھر جانے سے ڈر",
  "جان كا خطرہ",
  "زبردستي",
  "ظلم ہوتا ہے",
  "حبس بے جا",
  "گلا دبايا",
  "شوہر مارتا ہے كيا طلاق گناہ ہے",
  "باپ ظلم كرتا ہے",
  "صبر كا حكم",
  "مجازي خدا",
  // ── AR ──
  "العنف الاسري",
  "عنف اسري",
  "اهلي يعذبوني",
  "ابوي يطقني",
  "ضرب مبرح",
  "خايفه من زوجي",
  "يهددني",
  "محبوسه بالبيت",
  "غصبوني",
  "ضربني",
  "زوجي يطقني",
  "خايفه ارجع البيت",
  "حابسني",
  "بيهددني",
  "مغصوبه علي الزواج",
  "طاعه الزوج الظالم",
  "ابي يظلمني",
  "هل يجوز قطع صله الرحم",

  // ── WO#264 — fa dialect additions (Gem 5 string + Gem 3 tier) ──
  // dialect additions — Gem 5 string + Gem 3 tier (fa abuse), WO#264
  'من را میزند',
  'میترسم بروم خانه',
  'به من تجاوز کرد',

  // ── Punjabi / Shahmukhi (pa) — WO#284 (Gem 2 byte-verified) ─────────
  // Full abuse-disclosure phrases. Two suppress nouns are substrings here
  // (ظلم ⊂ بڑا ظلم کردا اے / گھر آلے ظلم کردے نیں ; مار ⊂ ماردا / مار مار کے).
  // These fire abuse directly — the substring never cancels the disclosure,
  // because SELF_HARM/ABUSE are matched before any suppression gate.
  'اوہ مینوں ماردا اے',
  'مینوں کٹ پیندی اے',
  'بڑا ظلم کردا اے',
  'مینوں مار مار کے',
  'گھر آلے ظلم کردے نیں',
  'مینوں ڈر لگدا اے اوس توں',
  'گھر جان توں ڈر لگدا اے',
  'مینوں قید کیتا ہویا اے',

  // ── Punjabi / Shahmukhi (pa) — WO#308 (Gem 5 verified) ─────
  // khawand (husband) register, hand-raise idiom, and beat-verbs (kutiya / mar-kutai)
  // absent from the WO#284 block. Full disclosure phrases; substring matching means
  // 'sohre mar kutai' is already covered by 'mar kutai' — both retained per ratification.
  'خاوند ماردا',
  'خاوند نے ماریا',
  'گھر والا ماردا',
  'ہتھ چکدا اے',
  'میرے تے ہتھ چکیا',
  'مینوں کٹیا',
  'مار کٹائی',
  'کٹ مار',
  'سوہرے مار کٹائی',
  'سوہریاں نے کٹیا',
  'سوہرے ماردے',
]

/**
 * WO#284 — Punjabi (pa) substring-collision nouns (Shahmukhi, Gem 2 verified).
 *
 * These common nouns are SUBSTRINGS of the pa intent phrases (e.g.
 * ظلم ⊂ بڑا ظلم کردا اے, مار ⊂ مینوں مار مار کے). They are deliberately NOT
 * crisis triggers: each fires nothing when alone (it is in no keyword list),
 * and it is NOT used as a stripping suppressor. The guard-before-trigger
 * precedence is the EXISTING detectCrisis ordering — SELF_HARM_KEYWORDS and
 * ABUSE_KEYWORDS are matched (matchesAnyExcept) before any suppression gate is
 * reached — so a full intent phrase always wins over its own suppress-substring.
 * Exported for the crisis-mechanics regression suite (precedence proof).
 */
export const PA_SUPPRESS: ReadonlyArray<string> = [
  'موت',
  'مرنا',
  'جنازہ',
  'قبر',
  'ظلم',
  'مار',
  'دکھ',
  'صبر',
]


/**
 * WO#252-B — FP-guard precedence phrases (Arabic, pre-normalised).
 *
 * A crisis trigger that is a *substring* of a valid Qur'anic / devotional
 * phrase (trigger ⊂ guard) must not fire when the user typed the longer
 * phrase. detectCrisis strips these guard phrases from the normalised input
 * before keyword matching, so the trigger inside the guard disappears while
 * any independent trigger elsewhere in the text still fires.
 *
 * Only "ya laytani muttu" / "...qabla hadha" (Qur'an 19:23, Maryam) needs
 * this today — the FP-guard set (§2) is safe by omission (no trigger is a
 * substring of any of them; asserted in crisis-mechanics.test.ts).
 */
export const SELF_HARM_GUARDS: ReadonlyArray<string> = [
  "يا ليتني مت قبل هذا",
]

import { normaliseArabic, containsArabic } from './arabic-normalise.js'
import { foldLatin } from './latin-fold.js'

/**
 * WO#308 — apostrophe normalisation. Contraction keywords ("don't want to be
 * alive", "can't go on", "i'm a burden", "wish i wasn't here") silently missed
 * the extremely common apostrophe-free mobile spelling ("dont", "cant", "im",
 * "wasnt"). Stripping every apostrophe variant (straight ' , curly ’ , grave ` ,
 * acute ´ , modifier ʼ) from BOTH the folded input and the folded keyword makes
 * the already-reviewed phrases fire on either spelling. FP-neutral: it only
 * removes a character, it never adds a new match surface. Applied in both
 * matchesAny and matchesAnyExcept, so it covers SELF_HARM_KEYWORDS and
 * ABUSE_KEYWORDS alike.
 */
function stripApostrophes(s: string): string {
  return s.replace(/['’`´ʼ]/g, '')
}

/**
 * Apply detection over a keyword list. Arabic-script keywords match against
 * `normaliseArabic(input)` (incl. the WO#252-A cross-script fold); Latin /
 * transliterated keywords match against the Turkish/Latin-folded lower-cased
 * input (WO#97 §S3D + WO#252-A).
 *
 * Both the keyword and the input are folded the same way, so a diacritic-free
 * "olmek istiyorum" matches the stored "ölmek istiyorum" and vice versa. The
 * normalise/fold calls on the keyword are defensive — the stored entries are
 * already in canonical form, but re-applying is idempotent and protects against
 * a contributor adding a non-canonical keyword by accident.
 */
function matchesAny(
  keywords: ReadonlyArray<string>,
  folded: string,
  normArabic: string
): boolean {
  for (const k of keywords) {
    if (containsArabic(k)) {
      if (normArabic.includes(normaliseArabic(k))) return true
    } else {
      if (folded.includes(stripApostrophes(foldLatin(k)))) return true
    }
  }
  return false
}

/**
 * Detect crisis keywords in user input.
 * Self-harm is checked first (higher acuity).
 *
 * Two normalisation passes on the input, applied once and shared
 * across both keyword-list checks:
 *   - `lower`        — toLowerCase() for English / transliterated
 *                      Arabic / Indonesian / Urdu keywords. Acronym
 *                      keywords like `'kdrt'` rely on this.
 *   - `normArabic`   — Arabic-specific normalisation (WO#97 §S3D)
 *                      so chat-typed Arabic without hamza / tashkeel
 *                      matches the formal-MSA keyword spellings.
 */
/**
 * WO#265 — bare-noun frame-suppression (Gem 2 four-gate, Architect-tightened).
 *
 * These 6 crisis keywords are common informational / fiqh lookups when bare
 * ("is X haram", "definition of X"), so a LONE hit on one of them is gated: it
 * FIRES unless an informational-frame marker is present, NO disclosure marker is
 * present, and the input is <= 8 words. Any co-occurring crisis trigger (gate 1),
 * any disclosure marker (gate 3), or > 8 words (gate 4) => FIRE. Suppression is
 * the catastrophic direction, so every ambiguous branch defaults to FIRE. Applies
 * to THESE 6 ONLY — every other crisis keyword fires exactly as before. Markers
 * run through the SAME normalisation pipeline (WO#263 ZWNJ/NFC/fold) via matchesAny.
 */
export const BARE_NOUN_GUARDS: ReadonlyArray<{ kw: string; type: 'self-harm' | 'abuse'; locale: 'fa' | 'bn' }> = [
  { kw: "خودکشی", type: 'self-harm', locale: 'fa' },
  { kw: "خشونت خانگی", type: 'abuse', locale: 'fa' },
  { kw: "ازار جنسی", type: 'abuse', locale: 'fa' },
  { kw: "আত্মহত্যা", type: 'self-harm', locale: 'bn' },
  { kw: "পারিবারিক সহিংসতা", type: 'abuse', locale: 'bn' },
  { kw: "যৌন নির্যাতন", type: 'abuse', locale: 'bn' },
]
const BARE_NOUN_SET = new Set<string>(BARE_NOUN_GUARDS.map((g) => g.kw))

// Gem 2 marker sets (exported so the QA matrix builds cases from the real data).
export const FA_FRAME_MARKERS: ReadonlyArray<string> = ["حکم", "گناه", "مجازات", "تعریف", "چیست", "ایا", "حرام", "حلال", "جایز", "اسلام", "دین", "شرع", "قران", "قانون", "کفاره", "عذاب", "دیه", "شرایط", "گناهش"]
export const FA_DISCLOSURE_MARKERS: ReadonlyArray<string> = ["من", "میخواهم", "میخوام", "خسته", "شدم", "کردم", "کمک", "نجات", "شوهرم", "پدرم", "خانوادم", "برادرم", "زنم", "دیگه", "نمیتونم", "نمیخوام", "خودم", "بمیرم", "کشتن", "بکشم", "کتک", "زد", "درد", "میترسم", "تهدید", "خون"]
export const BN_FRAME_MARKERS: ReadonlyArray<string> = ["কি", "কী", "পাপ", "শাস্তি", "আইন", "ইসলামে", "ইসলামী", "হারাম", "জায়েজ", "জায়েয", "হুকুম", "বিধান", "কুরআনে", "হাদিসে", "সংজ্ঞা", "কাফফারা", "অপরাধ", "অধিকার"]
export const BN_DISCLOSURE_MARKERS: ReadonlyArray<string> = ["আমি", "আমার", "আমাকে", "চাই", "কষ্ট", "পারছি", "বাঁচতে", "সাহায্য", "স্বামী", "বাবা", "পরিবার", "ভাই", "স্ত্রী", "মরে", "মরতে", "নিজেকে", "আর", "সহ্য", "খুব", "মেরেছে", "মারধর", "ভয়"]
const FRAME_MARKERS: ReadonlyArray<string> = [...FA_FRAME_MARKERS, ...BN_FRAME_MARKERS]
const DISCLOSURE_MARKERS: ReadonlyArray<string> = [...FA_DISCLOSURE_MARKERS, ...BN_DISCLOSURE_MARKERS]

/** matchesAny but skipping any keyword in `exclude` (the bare-noun set). */
function matchesAnyExcept(
  keywords: ReadonlyArray<string>, exclude: Set<string>, folded: string, normArabic: string,
): boolean {
  for (const k of keywords) {
    if (exclude.has(k)) continue
    if (containsArabic(k)) { if (normArabic.includes(normaliseArabic(k))) return true }
    else { if (folded.includes(stripApostrophes(foldLatin(k)))) return true }
  }
  return false
}

/** Distinct bare-noun guards that hit the (normalised) input. */
function bareNounHits(folded: string, normArabic: string): Array<{ kw: string; type: CrisisType }> {
  const hits: Array<{ kw: string; type: CrisisType }> = []
  for (const g of BARE_NOUN_GUARDS) {
    const hit = containsArabic(g.kw)
      ? normArabic.includes(normaliseArabic(g.kw))
      : folded.includes(foldLatin(g.kw))
    if (hit) hits.push({ kw: g.kw, type: g.type })
  }
  return hits
}

function wordCount(text: string): number {
  const t = text.trim()
  return t ? t.split(/\s+/).length : 0
}

/**
 * Gates 2-4 for a lone bare-noun hit (gate 1 is handled by the caller).
 * true = FIRE crisis, false = SUPPRESS (informational frame, no disclosure, short).
 */
function fireBareNoun(text: string, folded: string, normArabic: string): boolean {
  if (!matchesAny(FRAME_MARKERS, folded, normArabic)) return true       // gate 2: no frame => FIRE
  if (matchesAny(DISCLOSURE_MARKERS, folded, normArabic)) return true   // gate 3: disclosure => FIRE
  return wordCount(text) > 8                                            // gate 4: <=8 SUPPRESS, >8 FIRE
}

export function detectCrisis(text: string): CrisisDetectionResult {
  // WO#252-A — Latin branch: lower-case then Turkish/Latin-fold once, shared
  // across both keyword-list checks so diacritic-free input (and dotted/dotless
  // İ/ı) matches the stored diacritic forms.
  const folded = stripApostrophes(foldLatin(text.toLowerCase()))
  let normArabic = normaliseArabic(text)
  // WO#252-B — FP-guard precedence: strip guard phrases so a trigger that is a
  // substring of a valid Qur'anic/devotional phrase does not fire when the user
  // typed the longer phrase. Independent triggers elsewhere are untouched.
  for (const guard of SELF_HARM_GUARDS) {
    if (guard) normArabic = normArabic.split(guard).join('')
  }


  // WO#265 — non-bare crisis strings fire exactly as before (gate 1: a
  // co-occurring non-bare trigger short-circuits here).
  if (matchesAnyExcept(SELF_HARM_KEYWORDS, BARE_NOUN_SET, folded, normArabic)) {
    return { isCrisis: true, crisisType: 'self-harm' }
  }
  if (matchesAnyExcept(ABUSE_KEYWORDS, BARE_NOUN_SET, folded, normArabic)) {
    return { isCrisis: true, crisisType: 'abuse' }
  }
  // Only bare-noun guards can match now — apply the four-gate suppression.
  const hits = bareNounHits(folded, normArabic)
  if (hits.length === 0) return { isCrisis: false, crisisType: 'none' }
  const type: CrisisType = hits.some((h) => h.type === 'self-harm') ? 'self-harm' : 'abuse'
  if (hits.length >= 2) return { isCrisis: true, crisisType: type } // gate 1: 2+ distinct bare nouns
  if (fireBareNoun(text, folded, normArabic)) return { isCrisis: true, crisisType: type }
  return { isCrisis: false, crisisType: 'none' } // suppressed: informational frame
}
