// ─────────────────────────────────────────────────────────────────
// SYNCED FILE — DO NOT EDIT BY HAND.
// Generated by mcp-server/scripts/bundle-data.ts from the main
// Sakina app. Source of truth: ../../../src/lib/utils/<filename>.
// Run `npm run bundle-data` to refresh.
// ─────────────────────────────────────────────────────────────────

/**
 * Turkish / Latin diacritic fold (WO#252-A).
 *
 * Collapses the Turkish-specific Latin letters onto their ASCII base so a user
 * who types diacritic-free ("olmek istiyorum", "intihar") matches the stored
 * diacritic form ("ölmek istiyorum"), and dotted/dotless I variants stop
 * mismatching. Applied AFTER lowercasing, to BOTH the input and the (Latin)
 * keyword in the crisis / distress substring matchers.
 *
 *   ı/İ → i   ş → s   ç → c   ğ → g   ö → o   ü → u
 *
 * A default `toLowerCase()` maps the dotted capital İ to "i̇" (i + U+0307
 * combining dot above) rather than a bare i, so the fold also strips U+0307 —
 * this is the "locale-safe lowercasing" the detector needs WITHOUT applying a
 * blanket `toLocaleLowerCase('tr')` (which would wrongly turn an English "I"
 * into "ı" and corrupt the English keyword match).
 *
 * ASCII and non-Latin scripts pass through unchanged (Arabic-script keywords go
 * through `normaliseArabic` instead), so this is safe to apply unconditionally.
 */
const LATIN_FOLD_MAP: Record<string, string> = {
  ı: 'i', İ: 'i', I: 'i',
  ş: 's', Ş: 's',
  ç: 'c', Ç: 'c',
  ğ: 'g', Ğ: 'g',
  ö: 'o', Ö: 'o',
  ü: 'u', Ü: 'u',
}

const COMBINING_DOT_ABOVE = /̇/g

export function foldLatin(input: string): string {
  if (!input) return ''
  let out = ''
  for (const ch of input.normalize('NFC')) {
    out += LATIN_FOLD_MAP[ch] ?? ch
  }
  return out.replace(COMBINING_DOT_ABOVE, '')
}
