/**
 * Bundle data for standalone MCP server deployment (WO#105 Task 1).
 *
 * The MCP server cannot ship with `../src/...` imports — when
 * published as @asksakina/islamic-knowledge-mcp, the consumer's
 * machine doesn't have the main Sakina monorepo. This script
 * snapshots the required content + safety logic into the package's
 * own `data/` and `src/safety/_synced/` directories.
 *
 * Outputs:
 *   - `mcp-server/data/duas.json`            — the du'a corpus, Gem-2-verified Quranic entries labelled (quranic-labels.ts)
 *   - `mcp-server/data/names.json`           — 99 Names of Allah
 *   - `mcp-server/data/dua-categories.json`  — DUA_CATEGORIES metadata
 *   - `mcp-server/src/safety/_synced/crisis-detection.ts`
 *   - `mcp-server/src/safety/_synced/arabic-normalise.ts`
 *
 * Why synced TS files (not just keyword JSON): the main app's
 * `detectCrisis` is the canonical safety contract — Gem 3 + Gem 5
 * have signed off on its exact phrase matching, not just on a flat
 * keyword list. Re-implementing the matcher in the MCP server would
 * risk silent drift. Snapshotting the source preserves the contract;
 * a future divergence shows up clearly in `git diff` against the
 * synced files.
 *
 * Run: `npm run bundle-data` from `mcp-server/`. Wired into
 * `prepublishOnly` so `npm publish` always re-bundles first.
 */

import { promises as fs } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { ALL_DUAS, DUA_CATEGORIES } from '../../src/data/duas/index.js'
import { namesOfAllah } from '../../src/lib/data/99-names.js'
import { QURANIC_LABELS, skeleton } from './quranic-labels.js'

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(SCRIPT_DIR, '..')
const MAIN_REPO = path.resolve(ROOT, '..')
const OUT_DATA_DIR = path.join(ROOT, 'data')
const OUT_SYNCED_DIR = path.join(ROOT, 'src', 'safety', '_synced')

const SYNCED_HEADER = `// ─────────────────────────────────────────────────────────────────
// SYNCED FILE — DO NOT EDIT BY HAND.
// Generated by mcp-server/scripts/bundle-data.ts from the main
// Sakina app. Source of truth: ../../../src/lib/utils/<filename>.
// Run \`npm run bundle-data\` to refresh.
// ─────────────────────────────────────────────────────────────────
`

async function ensureDir(dir: string) {
  await fs.mkdir(dir, { recursive: true })
}

async function writeJson(file: string, payload: unknown) {
  const json = JSON.stringify(payload, null, 2)
  await fs.writeFile(file, json, 'utf-8')
  const bytes = Buffer.byteLength(json, 'utf-8')
  console.log(`  wrote ${path.relative(ROOT, file)} (${(bytes / 1024).toFixed(1)} KB)`)
}

async function copySyncedTypeScript(srcRel: string, dest: string, rewrites: Array<[string, string]>) {
  const srcPath = path.join(MAIN_REPO, srcRel)
  let content = await fs.readFile(srcPath, 'utf-8')
  for (const [from, to] of rewrites) {
    content = content.split(from).join(to)
  }
  // Strip any sentinel JSDoc that references monorepo-internal paths
  // and prepend the synced header so the file is self-describing.
  await fs.writeFile(dest, SYNCED_HEADER + '\n' + content, 'utf-8')
  console.log(`  synced ${path.relative(ROOT, dest)}`)
}

// WO#377 addendum: label Gem-2-verified Quranic du'as and resolve their
// Arabic from the scripture module. Output only; the corpus is not edited.
function labelQuranicDuas() {
  const byId = new Map(QURANIC_LABELS.map((l) => [l.id, l]))
  const seen = new Set<string>()
  const out = ALL_DUAS.map((dua) => {
    const label = byId.get(dua.id)
    if (!label) return dua
    seen.add(dua.id)
    const arabic = label.resolve()
    if (skeleton(arabic) !== skeleton(dua.arabic)) {
      throw new Error(
        `quranic label ${dua.id}: corpus Arabic no longer matches Quran ${label.ref}; re-verify with Gem 2 before labelling`,
      )
    }
    return { ...dua, arabic, origin: 'quran' as const, quran_ref: label.ref }
  })
  const missing = QURANIC_LABELS.filter((l) => !seen.has(l.id)).map((l) => l.id)
  if (missing.length) throw new Error(`quranic labels for unknown du'a ids: ${missing.join(', ')}`)
  console.log(`  labelled ${seen.size} du'as origin=quran (scripture module Arabic)`)
  return out
}

async function bundleDuas() {
  console.log(`bundling du'as (${ALL_DUAS.length} entries, ${DUA_CATEGORIES.length} categories)`)
  await writeJson(path.join(OUT_DATA_DIR, 'duas.json'), labelQuranicDuas())
  await writeJson(path.join(OUT_DATA_DIR, 'dua-categories.json'), DUA_CATEGORIES)
}

async function bundleNames() {
  console.log(`bundling 99 Names (${namesOfAllah.length} entries)`)
  await writeJson(path.join(OUT_DATA_DIR, 'names.json'), namesOfAllah)
}

async function syncSafetyFiles() {
  console.log('syncing safety logic')
  await copySyncedTypeScript(
    'src/lib/utils/arabic-normalise.ts',
    path.join(OUT_SYNCED_DIR, 'arabic-normalise.ts'),
    [],
  )
  await copySyncedTypeScript(
    'src/lib/utils/latin-fold.ts',
    path.join(OUT_SYNCED_DIR, 'latin-fold.ts'),
    [],
  )
  await copySyncedTypeScript(
    'src/lib/utils/crisis-detection.ts',
    path.join(OUT_SYNCED_DIR, 'crisis-detection.ts'),
    [
      // Rewrite the @/ aliases to relative imports inside _synced/.
      ["import { normaliseArabic, containsArabic } from '@/lib/utils/arabic-normalise'",
       "import { normaliseArabic, containsArabic } from './arabic-normalise.js'"],
      ["import { foldLatin } from '@/lib/utils/latin-fold'",
       "import { foldLatin } from './latin-fold.js'"],
    ],
  )
}

async function writeManifest() {
  const manifest = {
    generatedAt: new Date().toISOString(),
    counts: {
      duas: ALL_DUAS.length,
      duaCategories: DUA_CATEGORIES.length,
      names: namesOfAllah.length,
    },
    notes: [
      'Generated by mcp-server/scripts/bundle-data.ts.',
      'Quran verses are NOT bundled: fetched at runtime from alquran.cloud (en.pickthall / Pickthall).',
      'Pastoral Care content is NOT bundled: held back from agent surface (see docs/mcp-phase-3-planning.md).',
    ],
  }
  await writeJson(path.join(OUT_DATA_DIR, 'manifest.json'), manifest)
}

async function main() {
  console.log('Sakina MCP — bundle-data')
  await ensureDir(OUT_DATA_DIR)
  await ensureDir(OUT_SYNCED_DIR)
  await bundleDuas()
  await bundleNames()
  await syncSafetyFiles()
  await writeManifest()
  console.log('done.')
}

main().catch((err) => {
  console.error('bundle-data FAILED:', err)
  process.exit(1)
})
