/**
 * 99 Names of Allah loader for the MCP server (WO#102, repackaged
 * in WO#105).
 *
 * Reads from `data/names.json`, generated by `scripts/bundle-data.ts`
 * from the main Sakina monorepo's canonical list at publish time.
 */

import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const DATA_DIR = path.resolve(HERE, '..', '..', 'data')

interface BundledName {
  number: number
  arabic: string
  transliteration: string
  meaning: { en: string; ar?: string; ur: string; id: string }
  description: { en: string; ar?: string; ur: string; id: string }
  quranReferences?: string[]
  dhikrBenefit?: string
}

const namesOfAllah = JSON.parse(readFileSync(path.join(DATA_DIR, 'names.json'), 'utf-8')) as BundledName[]

export type SupportedLocale = 'en' | 'id' | 'ur' | 'ar'

export interface NameRecord {
  /**
   * Pre-formatted, inseparable display block (Gem 10 fix 6,
   * 2026-05-08). Couples every field a calling agent might be
   * tempted to drop. The presentation contract instructs the agent
   * to prefer this over reassembling from the structured keys.
   */
  name_block: string
  number: number
  arabic: string
  transliteration: string
  english_meaning: string
  reflection: string
  quranic_references: string[]
}

function sanitise(input: string): string {
  return input.split('\u{FDFA}').join(' (peace be upon him)').trim()
}

function meaningFor(name: BundledName, locale: SupportedLocale): string {
  if (locale === 'en') return name.meaning.en
  if (locale === 'ur') return name.meaning.ur
  if (locale === 'id') return name.meaning.id
  return name.meaning.ar ?? name.meaning.en
}

function descriptionFor(name: BundledName, locale: SupportedLocale): string {
  if (locale === 'en') return name.description.en
  if (locale === 'ur') return name.description.ur
  if (locale === 'id') return name.description.id
  return name.description.ar ?? name.description.en
}

function toRecord(name: BundledName, locale: SupportedLocale): NameRecord {
  const englishMeaning = sanitise(meaningFor(name, locale))
  const reflection = sanitise(descriptionFor(name, locale))
  const quranic_references = name.quranReferences ?? []

  const refLine =
    quranic_references.length > 0
      ? `Quranic Reference: ${quranic_references.map((r) => `Quran ${r}`).join('; ')}`
      : null
  const name_block = [
    `Arabic: ${name.arabic}`,
    `Transliteration: ${name.transliteration}`,
    `Meaning: ${englishMeaning}`,
    `Reflection: ${reflection}`,
    refLine,
  ]
    .filter(Boolean)
    .join('\n')

  return {
    name_block,
    number: name.number,
    arabic: name.arabic,
    transliteration: name.transliteration,
    english_meaning: englishMeaning,
    reflection,
    quranic_references,
  }
}

export function getNameByNumber(num: number, locale: SupportedLocale): NameRecord | null {
  const found = namesOfAllah.find((n) => n.number === num)
  return found ? toRecord(found, locale) : null
}

export function findNameByString(input: string, locale: SupportedLocale): NameRecord | null {
  const normalised = stripDiacritics(input).toLowerCase().trim()

  const asNumber = Number(input)
  if (Number.isInteger(asNumber) && asNumber >= 1 && asNumber <= 99) {
    return getNameByNumber(asNumber, locale)
  }

  for (const name of namesOfAllah) {
    if (stripDiacritics(name.transliteration).toLowerCase() === normalised) {
      return toRecord(name, locale)
    }
    if (name.arabic === input.trim()) return toRecord(name, locale)
  }

  for (const name of namesOfAllah) {
    if (name.meaning.en.toLowerCase().includes(normalised)) {
      return toRecord(name, locale)
    }
  }

  return null
}

function stripDiacritics(s: string): string {
  return s.normalize('NFD').replace(/\p{M}/gu, '')
}

export const TOTAL_NAMES = namesOfAllah.length
